#SKQuery with errors in console
#on shoot:
#    trail projectile with particle drip lava

# SKript
#
#show wolf hearts on the clicked wolf
#
#BARRIER
#BLOCK_CRACK
#BLOCK_DUST    
#CLOUD  		   
#CRIT  		   
#CRIT_MAGIC  		   
#DRIP_LAVA  		   
#DRIP_WATER  		   
#ENCHANTMENT_TABLE  		   
#EXPLOSION_HUGE  		   
#EXPLOSION_LARGE  		   
#EXPLOSION_NORMAL  		   
#FIREWORKS_SPARK  		   
#FLAME  		  
#FOOTSTEP  		   
#HEART  		 
#ITEM_CRACK  		 
#ITEM_TAKE  		 
#LAVA  		   
#MOB_APPEARANCE  		   
#NOTE  		    
#PORTAL  		   
#REDSTONE  		  
#SLIME  		   
#SMOKE_LARGE  		   
#SMOKE_NORMAL  		   
#SNOW_SHOVEL  		   
#SNOWBALL  		 
#SPELL  		 
#SPELL_INSTANT  		 
#SPELL_MOB  		 
#SPELL_MOB_AMBIENT  		 
#SPELL_WITCH  
#SUSPENDED  		   
#SUSPENDED_DEPTH  
#TOWN_AURA  		   
#VILLAGER_ANGRY  		   
#VILLAGER_HAPPY  		   
#WATER_BUBBLE  		   
#WATER_DROP  		   
#WATER_SPLASH  
#WATER_WAKE  
#command /particle:
#	trigger:
#		play mob spawner flames at the targeted block to the player

#on any move:
#	if player meets betonquest condition "builder":
#		spawn 2 FLAME particles at location of player for player offset by 0.4, 0.7, 0.4
#	else if player meets betonquest condition "moderator":
#		spawn 2 SMOKE_NORMAL particles at location of player for player offset by 0.4, 0.7, 0.4
#	if player meets betonquest condition "creator":
#		spawn 2 of particle flame at location of player
#	if player meets betonquest condition "founder":
#		show 2 FLAME particles at location of player for all players witin 50 meters of the player offset by 0.4, 0.7, 0.4

#command /redemarrer:
#	trigger:
#		loop players:
#			message "&a&lLe serveur va redémarrer dans 60 secondes !"
#			message "&aNous serons de retour dans quelques instants."
#			message "&a&oMerci de ne pas spammer la reconnection."
#			wait 60 seconds
#			message "&c&o2"
#			kick loop-player because "&aGaïa revient dans quelques instants."
#		restart server
# There has to be a restart.sh !!
#
#
#Ne fonctionne qu'avec des items de base, pas de custom recipies
#on craft:
#	message "Warm for your feet!"
#
#
#	loop {email.list::*}:
#		if difference between {last.logout.%loop-value%} and now is smaller than 3 days:
#			stop
#		else:
#			if {last.logout.mailed.%loop-value%} is 1:
#				stop
#			else:
#				add 1 to {last.logout.mailed.%loop-value%}
#				send email with subject "Bonjour %loop-value% ! Nous avons remarqué que ça fait plus d'un mois que vous ne vous êtes pas connecté ! Revenez nous voir rapidement à l'adresse IP: gaia.craft.gg" with message "Vous manquez à Gaïa !" to "%{email.%loop-value%}%"
#		
#		if difference between {last.logout.%loop-value%} and now is smaller than 5 days:
#			stop
#		else:
#			if {last.logout.mailed.%loop-value%} is 2:
#				stop
#			else:
#				add 1 to {last.logout.mailed.%loop-value%}
#				send email with subject "Bonjour %loop-value% ! Nous avons remarqué que ça fait plus de trois mois que vous ne vous êtes pas connecté ! Revenez nous voir rapidement à l'adresse IP: gaia.craft.gg" with message "Vous manquez à Gaïa !" to "%{email.%loop-value%}%"

#
#
#%string% parsed as date[ formatted as %-string%]
#parses a string date as a date

#(year|month|month name|day of year|day of month|day of week|day name|hours|minutes|seconds) from date %date%
#date %date%'s (year|month|month name|day of year|day of month|day of week|day name|hours|minutes|seconds)
#gets information from a date


#
# This functions.
#
#command /totallyuselesstimecommandthatWORKS:
#	trigger:
#		set {_tmpO} to now
#		if "%day name from date {_tmpO}%" is "WEDNESDAY":
#			broadcast "WEDNESDAY"
#		else:
#			broadcast "Date: %{_tmpO}%"
#			broadcast "Year: %year from date {_tmpO}%"
#			broadcast "Month: %month from date {_tmpO}%"
#			broadcast "Month Name: %month name from date {_tmpO}%"
#			broadcast "Day of Year: %day of year from date {_tmpO}%"
#			broadcast "Day of Month: %day of month from date {_tmpO}%"
#			broadcast "Day of Week: %day of week from date {_tmpO}%"
#			broadcast "Day Name: %day name from date {_tmpO}%"
#			broadcast "Hour: %hours from date {_tmpO}%"
#			broadcast "Minute: %minutes from date {_tmpO}%"
#			broadcast "Second: %seconds from date {_tmpO}%"
#			set {_tmpO} to now
#		set {day.index} to day of week from date {_tmpO}
#		message "%{day.index}%"

#command /teamtesting:
#	trigger:
#		set {redteam.%player%} to 1
#		message "Vous avez rejoint l'équipe &cRouge"
#command /teamtestingoff:
#	trigger:
#		set {redteam.%player%} to 0
#		message "Vous avez quitté l'équipe &cRouge"

	
#on damage:
#   {redteam.%victim%} is 1:
#        {redteam.%attacker%} is 1:
#            cancel event
#            send "&cCe joueur est dans ton équipe" to attacker
			
#shoot an arrow
#make the player shoot a creeper at speed 10
#shoot a pig from the creeper

#DETECTS BUT WEIRDLY
#on vehicle collide with entity:
#    if event-entity is a player:
#        message "Collision !" to player
#        make player damage event-entity by 2
#    if event-entity is a pig:
#        broadcast "Hit !"

#
#SAME AS ON LOGIN THIS DOES NOT DOWNLOAD PROPERLY		
#command /ressourcepacktester:
#	trigger:
#		send resourcepack "https://www.dropbox.com/s/drnvydf8xhile1y/MedievalDarkness.zip?dl=1" to player